### PR TITLE
Fixed assembly reference

### PR DESCRIPTION
**Pull request by mtscout6**
I fixed the WebKit.Interop dll reference to not be a bin/debug folder reference. This should allow other people to pull and build right off the bat.

### CODE REVIEW

**Comment by krazyjakee** [comment]
Can you push compiled versions of everything? I can't seem to get anything to compile and I just want to use it.

**Comment by mtscout6** [comment]
It is generally best practice for .Net projects to NOT push the compiled version of the code. That is what Nuget and many other package management solutions are for. I believe this is the case for most source code repositories. The correct thing to do would be to determine why it's not building on your machine and fix it, then submit a pull request. That was the intent of this pull request. I saw that the solution would not compile because the project was referencing an assembly within the "build" directory, which of course hasn't happened for those new to pulling the repo.

**Comment by krazyjakee** [comment]
I'm not that familiar with bug fixing other solutions in VS, for now I'll wait, thanks for the response.

**Comment by mtscout6** [comment]
What is the error you get when you try to compile?

**Comment by krazyjakee** [comment]
It's a little hard to explain.

First of all I went here https://github.com/webkitdotnet/webkitdotnet/pull/14 as I am just looking for a means to callback to c# from javascript. @jharwig mentioned his fork was working with callbacks so I downloaded his fork: https://github.com/jharwig/webkitdotnet

I open up WebKit.NET_2010.sln with V C# 2010 express and it mentions some folders are incompatable.

I go to build, knowing it will fail but I just want to see what it's actually looking for...

Error   1   Metadata file 'Desktop\jharwig-webkitdotnet-4a74cfb\bin\Debug\WebKitCore.dll' could not be found    WebKitBrowser
Warning 2   Could not resolve this reference. Could not locate the assembly "WebKit.Interop". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.   WebKitBrowser
Warning 3   The referenced component 'WebKit.Interop' could not be found.  
Error   4   The imported project "G:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.    Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\JSCore.vcxproj  18  3   WebKitBrowserTest
Warning 5   The referenced component 'JSCore' could not be found.  
Error   6   The imported project "G:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.    Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\JSCore.vcxproj  18  3   WebKitCore
Warning 7   The referenced component 'WebKit.Interop' could not be found.  
Warning 8   The referenced component 'JSCore' could not be found.

**Comment by mtscout6** [comment]
Yes, this is exactly what I was talking about the .csproj file is referencing assemblies in then bin folder, which doesn't exist until after you build everything. You need to change the location of those assemblies. If you expand references you will see an icon marking the ones that are referenced incorrectly. Just remove them then re-add them, you will need to find them in the directory tree, they will not be in the bin\Debug folder.

**Comment by krazyjakee** [comment]
I'll follow the instructions on the wiki.

**Comment by krazyjakee** [comment]
I'm using visual c++ 2010 express and following this: https://github.com/webkitdotnet/webkitdotnet/wiki/Building-WebKit.NET-with-Visual-Studio-2010-Express%3A-A-Visual-Step-By-Step-Guide.

Step 4 doesn't happen...

> It asks us where we would like to save the solution file. Don't save it in the JSCore folder! Save it in the repository's root folder.

it just throws up build errors.

> ------ Build started: Project: JSCore, Configuration: Release Win32 ------
> G:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.Targets(1360,9): warning MSB3245: Could not resolve this reference. Could not locate the assembly "WebKit.Interop, Version=533.0.0.0, Culture=neutral, PublicKeyToken=b967213f6d29a3be". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
>  Setting environment for using Microsoft Visual Studio 2010 x86 tools.
>  Microsoft (R) Visual C# 2010 Compiler version 4.0.30319.1
>  Copyright (C) Microsoft Corporation. All rights reserved.
> 
> EXEC : error CS2001: Source file 'G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\tools\TypeNormalizer.cs' could not be found
> EXEC : fatal error CS2008: No inputs specified
> TlbImp : error TI1009: The following error occurred while trying to open file G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\WebKit.NET.snk: System.IO.FileNotFoundException - Could not find file 'G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\WebKit.NET.snk'.
>  Unable to open 'G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\temp_webkit_interop.il' for output.
>  The system cannot find the path specified.
> 
>  Microsoft (R) .NET Framework IL Assembler.  Version 4.0.30319.1
>  Copyright (c) Microsoft Corporation.  All rights reserved.
>  Assembling 'G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\temp_webkit_interop.il'  to DLL --> 'G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\WebKit.Interop.dll'
>  Could not open G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\temp_webkit_interop.il
> 
>  ****\* FAILURE ****\* 
>  The system cannot find the file specified.
> G:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: The command "call "G:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE....\VC\vcvarsall.bat" x86
> G:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: if exist "G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\WebKit.Interop.dll" goto after_build_interop
> G:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: if not exist "G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\tools\TypeNormalizer.exe" csc /out:"G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\tools\TypeNormalizer.exe" "G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\tools\TypeNormalizer.cs"
> G:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: tlbimp "G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\webkit.tlb" /silent /keyfile:"G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\WebKit.NET.snk" /namespace:WebKit.Interop /out:"G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\WebKit.Interop.dll"
> G:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: ildasm "G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\WebKit.Interop.dll" /out="G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\temp_webkit_interop.il" /nobar
> G:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: "G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\tools\TypeNormalizer.exe" "G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\temp_webkit_interop.il"
> G:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: ilasm "G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\temp_webkit_interop.il" /dll /output="G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\WebKit.Interop.dll" /key="G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\WebKit.NET.snk"
> G:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: del /F /Q "G:\Users\User\Desktop\jharwig-webkitdotnet-4a74cfb\JSCore\webkit\temp_webkit_interop.*"
> G:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: :after_build_interop
> G:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(103,5): error MSB3073: :VCEnd" exited with code 1.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I get that it's looking for files that don't exist, but why doesn't the tutorial tell me where I can get them since they don't exist anywhere in the folder.

**Pull request merged**
