### PR TITLE
Fixes for ObjectForScripting

### PR DESCRIPTION
**Pull request by oyvindkinsey**
The ObjectForScripting property wasn't handled correctly, and objects dereferenced here would not show up in `window.external`.

These two patches corrects this, but the object that is available is not what's expected.
Using the native Browser control I was able to do 

```
browser.ObjectForScripting = this;
```

and all the public methods would be available on `window.external`, but now, what is available is a weird type of `function`, 

```
typeof external; // "function"
external.toString(); // "[object wrapper]"
```

Things might very well be as they should, but this wrapper object isn't marshalling any calls for me.

### CODE REVIEW

**Comment by jharwig** [comment]
Any success getting function calls working? I can only marshal properties – although custom getters do work.

**Comment by oyvindkinsey** [comment]
I've only tried with functions.. so properties work? 
Then at least we know that the plumbing work, now we need to figure out what the wrapper requires for marshalling function calls...

**Comment by jharwig** [comment]
I've made decent progress on the JS to C# bridge on my [fork](https://github.com/jharwig/webkitdotnet)

Support for function callbacks, field access, and nested objects are working

**Comment by oyvindkinsey** [comment]
Cool, I've been pulling in commits from different sources and also have a working fork, although I have not tested nested objects and such :)
You fork looks 'cleaner' though, so I'll have a look!

**Comment by Remo** [comment]
Anything new about these commits? They look good to me but I don't really have a lot of experience with WebKit. Anything I can do do make sure these pull requests get merged?

**Comment by peterdn** [comment]
I've merged jharwig's fork into the develop branch, so I believe most of these are now in there.

**Pull request closed without merging**
