### PR TITLE
Basic HTTP Authentication Support

### PR DESCRIPTION
**Pull request by therealmitchconnors**
Added support for Ignoring SSL Peer errors in WebKitBrowserTest/Program.cs using /IgnoreSSL CLArg.
Added support for Basic Authentication in each project, adding Username and Password properties to WebKitBrowser/WebKitBrowser.cs and WebKitCore/WebKitBrowserCore.cs, and UI elements under Edit in WebKitBrowserTest/MainForm.cs.
Added support for compiling WebKit.Interop.dll using build_webkit.interop_2010.bat.
Someone should probably make the browser throw errors on HTTP 401 and other error codes, so that a password dialog pops up and the request can be resent with the password, but that is beyond my capabilities.

### CODE REVIEW

**Comment by peterdn** [comment]
Looks good to me for the moment.  I've just pushed it.

Also just had a quick look, and I don't think there's an easy way of getting notified about HTTP 401 error codes at the moment (despite there being a couple of methods in ResourceLoadDelegate about authentication).

**Comment by therealmitchconnors** [comment]
Thanks.  I think I have already found a bug, however.  The Navigate() method
of webbrowsercore is only called when the user specifically provides a url
to the browser.  When a hyperlink is clicked, or a redirect is followed, the
navigate method is not called, and the navigate method is not fired.  Do you
know of any way to catch these events and get access within the event
handler to the WebRequest object for these navigations?  I am working on
digging through the WebKit source now to see what we can do, but six hours
in, I still do not have a successful build.  Bummer.  Anyways, thanks for
pulling my commit.  I hope to have a new pull request as soon as I fix this
latest bug.

therealmitchconnors

**Comment by peterdn** [comment]
Ah, you'll probably want WebPolicyDelegate.decidePolicyForNavigationAction in WebPolicyDelegate.cs which is called before any navigation action is taken.

Thanks for your help!  I could add you as a project member so you can commit code yourself, If you'd like.

**Comment by therealmitchconnors** [comment]
Thanks for the tip.  It would be great to be a project member, though I do
appreciate having my code reviewed a bit before it is pulled.

I tried using the WebPolicyDelegate, but apparently it is called after the
Authentication header is sent, because the server still returned a 401 error
when the username and password were set there.  I am currently digging into
the webkit source to see if there is an easier way to do this...

**Pull request merged**
